echo "Paris" | python url_encode.py
echo "Rome" | python url_encode.py
echo "Venice" | python url_encode.py
echo "Florence" | python url_encode.py
echo "Milan" | python url_encode.py
echo "Barcelona" | python url_encode.py
echo "Amsterdam" | python url_encode.py
echo "Munich" | python url_encode.py
echo "London" | python url_encode.py
echo "Vienna" | python url_encode.py
echo "Prague" | python url_encode.py
echo "Berlin" | python url_encode.py
echo "Frankfurt" | python url_encode.py
echo "Nice" | python url_encode.py
echo "Brussels" | python url_encode.py
echo "Lucerne" | python url_encode.py
echo "Madrid" | python url_encode.py
echo "Pisa" | python url_encode.py
echo "Zurich" | python url_encode.py
echo "Geneva" | python url_encode.py
echo "Interlaken" | python url_encode.py
echo "Cologne" | python url_encode.py
echo "Versailles" | python url_encode.py
echo "Salzburg" | python url_encode.py
echo "Stockholm" | python url_encode.py
echo "Edinburgh" | python url_encode.py
echo "Budapest" | python url_encode.py
echo "Copenhagen" | python url_encode.py
echo "Cambridge" | python url_encode.py
echo "Heidelberg" | python url_encode.py
echo "Oxford" | python url_encode.py
echo "Berne" | python url_encode.py
echo "Cannes" | python url_encode.py
echo "Luxembourg City" | python url_encode.py
echo "Sevilla" | python url_encode.py
echo "Lausanne" | python url_encode.py
echo "Avignon" | python url_encode.py
echo "Hamburg" | python url_encode.py
echo "Fussen" | python url_encode.py
echo "Bath" | python url_encode.py
echo "Brugge" | python url_encode.py
echo "Rotterdam" | python url_encode.py
echo "Lisbon" | python url_encode.py
echo "Manchester" | python url_encode.py
echo "Hague" | python url_encode.py
echo "Marseille" | python url_encode.py
echo "Helsinki" | python url_encode.py
echo "Lyon" | python url_encode.py
echo "Provence" | python url_encode.py
echo "York" | python url_encode.py
echo "Oslo" | python url_encode.py
echo "Verona" | python url_encode.py
echo "Dusseldorf|Dsseldorf" | python url_encode.py
echo "Naples" | python url_encode.py
echo "Cesky Krumlov" | python url_encode.py
echo "Innsbruck" | python url_encode.py
echo "Stuttgart" | python url_encode.py
echo "Granada" | python url_encode.py
echo "Hallstatt" | python url_encode.py
echo "Toledo" | python url_encode.py
echo "Birmingham" | python url_encode.py
echo "Siena" | python url_encode.py
echo "Antwerp" | python url_encode.py
echo "Lake District National Park" | python url_encode.py
echo "Glasgow" | python url_encode.py
echo "Montreux" | python url_encode.py
echo "Cinque Terre" | python url_encode.py
echo "Basle" | python url_encode.py
echo "Pompeii" | python url_encode.py
echo "Bonn" | python url_encode.py
echo "Bergen" | python url_encode.py
echo "Liverpool" | python url_encode.py
echo "Dresden" | python url_encode.py
echo "Fontainebleau" | python url_encode.py
echo "Giethoorn" | python url_encode.py
echo "Segovia" | python url_encode.py
echo "Stonehenge" | python url_encode.py
echo "Nuremberg" | python url_encode.py
echo "Berchtesgaden" | python url_encode.py
echo "Zermatt" | python url_encode.py
echo "Schwarzwald" | python url_encode.py
echo "Rothenburg" | python url_encode.py
echo "Baden-Baden" | python url_encode.py
echo "Sintra" | python url_encode.py
echo "Arles" | python url_encode.py
echo "Strasbourg" | python url_encode.py
echo "CORDOBA" | python url_encode.py
echo "Porto" | python url_encode.py
echo "Potsdam" | python url_encode.py
echo "Ghent" | python url_encode.py
echo "Valencia" | python url_encode.py
echo "Warsaw" | python url_encode.py
echo "Cardiff" | python url_encode.py
echo "Mount" | python url_encode.py
echo "Bordeaux" | python url_encode.py
echo "Brighton" | python url_encode.py
echo "Loch Ness" | python url_encode.py
echo "Wurzburg" | python url_encode.py
echo "Hannover" | python url_encode.py
echo "Dijon" | python url_encode.py
echo "Genoa" | python url_encode.py
echo "Bologna" | python url_encode.py
echo "Bremen" | python url_encode.py
echo "Gothenburg" | python url_encode.py
echo "Leeds" | python url_encode.py
echo "Bristol" | python url_encode.py
echo "Aachen" | python url_encode.py
echo "Annecy" | python url_encode.py
echo "Cracow" | python url_encode.py
echo "Koblenz" | python url_encode.py
echo "Isle of skye" | python url_encode.py
echo "Sognefjord" | python url_encode.py
echo "Loire Valley" | python url_encode.py
echo "Freiburg im Breisgau" | python url_encode.py
echo "Malmo" | python url_encode.py
echo "Malaga" | python url_encode.py
echo "Mainz" | python url_encode.py
echo "Lugano" | python url_encode.py
echo "Utrecht" | python url_encode.py
echo "Nottingham" | python url_encode.py
echo "Nimes" | python url_encode.py
echo "Constance" | python url_encode.py
echo "Amalfi" | python url_encode.py
echo "Sorrento" | python url_encode.py
echo "Karlovy Vary" | python url_encode.py
echo "Leipzig" | python url_encode.py
echo "Turin" | python url_encode.py
echo "Ronda" | python url_encode.py
echo "Lucca" | python url_encode.py
echo "Newcastle" | python url_encode.py
echo "Belfast" | python url_encode.py
echo "Bamberg" | python url_encode.py
echo "Lauterbrunnen" | python url_encode.py
echo "Mannheim" | python url_encode.py
echo "Sheffield" | python url_encode.py
echo "Spiez" | python url_encode.py
echo "Delft" | python url_encode.py
echo "Coventry" | python url_encode.py
echo "Essen" | python url_encode.py
echo "Rovaniemi" | python url_encode.py
echo "Inverness" | python url_encode.py
echo "Romantic Road" | python url_encode.py
echo "Augsburg" | python url_encode.py
echo "Toulouse" | python url_encode.py
echo "Maastricht" | python url_encode.py
echo "Aix en Provence" | python url_encode.py
echo "Como" | python url_encode.py
echo "Lille" | python url_encode.py
echo "Capri" | python url_encode.py
echo "Dortmund" | python url_encode.py
echo "Kutna Hora" | python url_encode.py
echo "Leiden" | python url_encode.py
echo "Trier" | python url_encode.py
echo "Murren" | python url_encode.py
echo "Tours" | python url_encode.py
echo "Roussillon" | python url_encode.py
echo "Linz" | python url_encode.py
echo "Lubeck" | python url_encode.py
echo "Grasse" | python url_encode.py
echo "Lysefjord" | python url_encode.py
echo "Southampton" | python url_encode.py
echo "San gimignano" | python url_encode.py
echo "Portsmouth" | python url_encode.py
echo "Isle of Wight" | python url_encode.py
echo "Grindelwald" | python url_encode.py
echo "Thun" | python url_encode.py
echo "Montpellier" | python url_encode.py
echo "Chester" | python url_encode.py
echo "Stavanger" | python url_encode.py
echo "Helsingborg" | python url_encode.py
echo "Vevey" | python url_encode.py
echo "Palermo" | python url_encode.py
echo "Bad ischl" | python url_encode.py
echo "St Andrews" | python url_encode.py
echo "Eze" | python url_encode.py
echo "Fort William" | python url_encode.py
echo "Fontaine-de-Vaucluse" | python url_encode.py
echo "Geirangerfjord" | python url_encode.py
echo "Ulm" | python url_encode.py
echo "Stirling" | python url_encode.py
echo "Chamonix" | python url_encode.py
echo "La Spezia" | python url_encode.py
echo "Carcassonne" | python url_encode.py
echo "Salamanca" | python url_encode.py
echo "Voss" | python url_encode.py
echo "Schaffhausen" | python url_encode.py
echo "Eindhoven" | python url_encode.py
echo "Reims" | python url_encode.py
echo "Flåm" | python url_encode.py
echo "Canterbury" | python url_encode.py
echo "Regensburg" | python url_encode.py
echo "Aberdeen" | python url_encode.py
echo "Weimar" | python url_encode.py
echo "kiruna" | python url_encode.py
echo "Metzingen" | python url_encode.py
echo "Colmar" | python url_encode.py
echo "Wengen" | python url_encode.py
echo "Nantes" | python url_encode.py
echo "Menton" | python url_encode.py
echo "Leicester" | python url_encode.py
echo "Odense" | python url_encode.py
echo "Brienzersee" | python url_encode.py
echo "Grenoble" | python url_encode.py
echo "Zaragoza" | python url_encode.py
echo "Rouen" | python url_encode.py
echo "Chenonceaux" | python url_encode.py
echo "Positano" | python url_encode.py
echo "Bilbao" | python url_encode.py
echo "Rimini" | python url_encode.py
echo "Mallorca" | python url_encode.py
echo "Elsinore" | python url_encode.py
echo "Groningen" | python url_encode.py
echo "Uppsala" | python url_encode.py
echo "Bournemouth" | python url_encode.py
echo "Cascais" | python url_encode.py
echo "Aarhus" | python url_encode.py
echo "Wolfsburg" | python url_encode.py
echo "Catania" | python url_encode.py
echo "Alesund" | python url_encode.py
echo "Bergamo" | python url_encode.py
echo "Brno" | python url_encode.py
echo "Lindau" | python url_encode.py
echo "Taormina" | python url_encode.py
echo "Caen" | python url_encode.py
echo "Normandie" | python url_encode.py
echo "Krems an der donau" | python url_encode.py
echo "Assisi" | python url_encode.py
echo "Geiranger" | python url_encode.py
echo "Turku" | python url_encode.py
echo "Perugia" | python url_encode.py
echo "Plymouth" | python url_encode.py
echo "Winchester" | python url_encode.py
echo "Engelberg" | python url_encode.py
echo "Blois" | python url_encode.py
echo "Wiesbaden" | python url_encode.py
echo "Tampere" | python url_encode.py
echo "Toulon" | python url_encode.py
echo "StGallen" | python url_encode.py
echo "Stratford upon Avon" | python url_encode.py
echo "Lund" | python url_encode.py
echo "Graz" | python url_encode.py
echo "Faro" | python url_encode.py
echo "Dover" | python url_encode.py
echo "Derby" | python url_encode.py
echo "Tromso" | python url_encode.py
echo "Saint Malo" | python url_encode.py
echo "Locarno" | python url_encode.py
echo "Nancy" | python url_encode.py
echo "Angers" | python url_encode.py
echo "Haarlem" | python url_encode.py
echo "Metz" | python url_encode.py
echo "Hardangerfjord" | python url_encode.py
echo "Melk" | python url_encode.py
echo "Vianden" | python url_encode.py
echo "Leuven" | python url_encode.py
echo "Duisburg" | python url_encode.py
echo "Abisko" | python url_encode.py
echo "Rennes" | python url_encode.py
echo "Amboise" | python url_encode.py
echo "Vicenza" | python url_encode.py
echo "San sebastian" | python url_encode.py
echo "Agrigento" | python url_encode.py
echo "Lancaster" | python url_encode.py
echo "Dundee" | python url_encode.py
echo "Bretagne" | python url_encode.py
echo "Amiens" | python url_encode.py
echo "Bari" | python url_encode.py
echo "Volendam" | python url_encode.py
echo "Santiago de composte" | python url_encode.py
echo "Gdańsk" | python url_encode.py
echo "Stein am Rhein" | python url_encode.py
echo "Ingolstadt" | python url_encode.py
echo "Garmisch-Partenkirchen" | python url_encode.py
echo "Parma" | python url_encode.py
echo "Modena" | python url_encode.py
echo "Arcachon" | python url_encode.py
echo "LOCH LOMOND" | python url_encode.py
echo "GIVERNY" | python url_encode.py
echo "Durham" | python url_encode.py
echo "Poznan" | python url_encode.py
echo "Leukerbad" | python url_encode.py
echo "Salisbury" | python url_encode.py
echo "Bohemia" | python url_encode.py
echo "Avila" | python url_encode.py
echo "Goettingen" | python url_encode.py
echo "Swansea" | python url_encode.py
echo "Erfurt" | python url_encode.py
echo "Salzkammergut" | python url_encode.py
echo "Lofoten" | python url_encode.py
echo "Chur" | python url_encode.py
echo "Calais" | python url_encode.py
echo "Bochum" | python url_encode.py
echo "Liege" | python url_encode.py
echo "Trondheim" | python url_encode.py
echo "Sion" | python url_encode.py
echo "Karlsruhe" | python url_encode.py
echo "Tarragona" | python url_encode.py
echo "Cuenca" | python url_encode.py
echo "Wroclaw" | python url_encode.py
echo "Bradford" | python url_encode.py
echo "Alicante" | python url_encode.py
echo "St. Moritz" | python url_encode.py
echo "Exeter" | python url_encode.py
echo "Linkoping" | python url_encode.py
echo "Passau" | python url_encode.py
echo "Conwy" | python url_encode.py
echo "Kemi" | python url_encode.py
echo "Cadiz" | python url_encode.py
echo "Ferrara" | python url_encode.py
echo "Coimbra" | python url_encode.py
echo "Munster" | python url_encode.py
echo "Bodo" | python url_encode.py
echo "Saint Andrew" | python url_encode.py
echo "Pilsen" | python url_encode.py
echo "Bregenz" | python url_encode.py
echo "cassel" | python url_encode.py
echo "Warwick" | python url_encode.py
echo "Brunswick" | python url_encode.py
echo "Antibes" | python url_encode.py
echo "Obertraun" | python url_encode.py
echo "Ruhr" | python url_encode.py
echo "Badeng" | python url_encode.py
echo "Ceske Budejovice" | python url_encode.py
echo "Le Havre" | python url_encode.py
echo "Namur" | python url_encode.py
echo "Magdeburg" | python url_encode.py
echo "Prato" | python url_encode.py
echo "Dinkelsbuhl" | python url_encode.py
echo "Narvik" | python url_encode.py
echo "Keswick" | python url_encode.py
echo "Messina" | python url_encode.py
echo "Piacenza" | python url_encode.py
echo "La Rochelle" | python url_encode.py
echo "Blackpool" | python url_encode.py
echo "Arnhem" | python url_encode.py
echo "Klagenfurt" | python url_encode.py
echo "Marken" | python url_encode.py
echo "Whitby" | python url_encode.py
echo "Troyes" | python url_encode.py
echo "Padova" | python url_encode.py
echo "Lungern" | python url_encode.py
echo "Sardinia" | python url_encode.py
echo "Kiel" | python url_encode.py
echo "Aurland" | python url_encode.py
echo "Lincoln" | python url_encode.py
echo "Mosel" | python url_encode.py
echo "Perth" | python url_encode.py
echo "Villefranche-sur-Mer" | python url_encode.py
echo "Dessau" | python url_encode.py
echo "Schwerin" | python url_encode.py
echo "Myrdal" | python url_encode.py
echo "Oulu" | python url_encode.py
echo "Grasmere" | python url_encode.py
echo "Brescia" | python url_encode.py
echo "Ancona" | python url_encode.py
echo "Roskilde" | python url_encode.py
echo "Ambleside" | python url_encode.py
echo "Bayeux" | python url_encode.py
echo "Stratford upon Avon" | python url_encode.py
echo "Neuchatel" | python url_encode.py
echo "Weggis" | python url_encode.py
echo "Beaune" | python url_encode.py
echo "Rostock" | python url_encode.py
echo "Siracusa" | python url_encode.py
echo "Oban" | python url_encode.py
echo "Aalborg" | python url_encode.py
echo "Brig" | python url_encode.py
echo "Trieste" | python url_encode.py
echo "Morges" | python url_encode.py
echo "Nyon" | python url_encode.py
echo "Coburg" | python url_encode.py
echo "Girona" | python url_encode.py
echo "Braga" | python url_encode.py
echo "Arezzo" | python url_encode.py
echo "Tuebingen" | python url_encode.py
echo "Poitiers" | python url_encode.py
echo "Pamplona" | python url_encode.py
echo "Rugen" | python url_encode.py
echo "Penzance" | python url_encode.py
echo "North Cape" | python url_encode.py
echo "Norwich" | python url_encode.py
echo "Jena" | python url_encode.py
echo "Davos" | python url_encode.py
echo "Lulea" | python url_encode.py
echo "Yorkshire Dales National Park" | python url_encode.py
echo "Clermont-Ferrand" | python url_encode.py
echo "Bellinzona" | python url_encode.py
echo "Dunkerque" | python url_encode.py
echo "Tivoli" | python url_encode.py
echo "Enschede" | python url_encode.py
echo "Albi" | python url_encode.py
echo "Saint-Paul-de-Vence" | python url_encode.py
echo "Santander" | python url_encode.py
echo "Hull" | python url_encode.py
echo "Limoges" | python url_encode.py
echo "Northamptonshire" | python url_encode.py
echo "Gudvangen" | python url_encode.py
echo "Meissen" | python url_encode.py
echo "Ravenna" | python url_encode.py
echo "Nijmegen" | python url_encode.py
echo "Evora" | python url_encode.py
echo "Saarbrücken" | python url_encode.py
echo "Breda" | python url_encode.py
echo "Fribourg" | python url_encode.py
echo "Livorno" | python url_encode.py
echo "Salerno" | python url_encode.py
echo "Friedrichshafen" | python url_encode.py
echo "Eisenstadt" | python url_encode.py
echo "Bayreuth" | python url_encode.py
echo "Burgos" | python url_encode.py
echo "Olomouc" | python url_encode.py
echo "Ibiza" | python url_encode.py
echo "Noto" | python url_encode.py
echo "Marbella" | python url_encode.py
